spring:
  application:
    name: threads-be

  datasource:
    url: ${POSTGRES_URI}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  jwt:
    secret: ${JWT_SECRET}
    access-exp: ${JWT_ACCESS_EXPIRES}
    refresh-exp: ${JWT_REFRESH_EXPIRES}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

google:
  client:
    id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_CLIENT_SECRET}
  redirect:
    uri: ${GOOGLE_REDIRECT_URI}

server:
  port: ${PORT}
  servlet:
    context-path:
      '/api'

logging:
  level:
    root: info
    viet.io.threads.security: debug

swagger:
  enabled: true
  title: Threads API
  description: Threads API Documentation
  version: 1.0
  contact:
    name: vietddude
    email: vietnd.works@gmail.com